CONTIKI_PROJECT = A-TXRXrate B C
all: $(CONTIKI_PROJECT)
CUSTOM_CFLAGS := -WALL CUSTOM_CFLAGS += -Wformat
WERROR := 0
CFLAGS += -DENERGEST_CONF_ON=1
MAKE_NET = MAKE_NET_NULLNET
#PROJECT_SOURCEFILES += PowerConsumption.c
CONTIKI=../..
include $(CONTIKI)/Makefile.include
